const INVENTORY_TYPES = {
  FETCH_INVENTORY_START: 'FETCH_INVENTORY_START',
  FETCH_INVENTORY_SUCCESS: 'FETCH_INVENTORY_SUCCESS',
  FETCH_INVENTORY_FAILURE: 'FETCH_INVENTORY_FAILURE',

  FETCH_GAME_DATA_START: 'FETCH_GAME_DATA_START',
  FETCH_GAME_DATA_SUCCESS: 'FETCH_GAME_DATA_SUCCESS',
  FETCH_GAME_DATA_FAILURE: 'FETCH_GAME_DATA_FAILURE',

  SET_CURRENT_GAMES_DISPLAY_START: 'SET_CURRENT_GAMES_DISPLAY_START',
  SET_CURRENT_GAMES_DISPLAY_SUCCESS: 'SET_CURRENT_GAMES_DISPLAY_SUCCESS',
  SET_CURRENT_GAMES_DISPLAY_FAILURE: 'SET_CURRENT_GAMES_DISPLAY_FAILURE',

  SET_FILTERED_GAMES: 'SET_FILTERED_GAMES'
};

export default INVENTORY_TYPES;
